name: books_app
description: Flutter Application based on book exchange

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.11.0
  flutter:
    sdk: flutter

  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  readmore: ^2.0.0
  google_fonts: ^1.1.1
  google_sign_in: "^4.5.1"
  flutter_login_facebook: ^0.4.2+3

  # mapbox_gl: ^0.10.0
  location: ^4.3.0
  provider: ^4.3.3
  image_picker: ^0.6.7+3
  image_cropper: ^1.4.0
  shared_preferences: ^0.5.3+4
  # geolocator: 6.2.1
  intl: ^0.17.0
  http: ^0.12.0+2
  geocoding: ^2.0.0
  # geocoder: ^0.2.1
  # latlong: ^0.8.0
  # geoflutterfire: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Explr Logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
